"""Claw-cam arrival check + pixel servo (three-object demo §3.2/§3.3).

Pure geometry + config — no camera, YOLO, or Modbus imports — so everything
here is testable off-rig against recorded episodes
(scripts/arrival_offline_eval.py) before the arm ever moves.

Runtime inputs:
  - boxes: ClawCameraService.get_detections() dicts
           {label, conf, x1, y1, x2, y2}  (coords normalized 0..1)
  - pred_step_mm: |Δxy| of the VLA's next intended move, or None when there
           is no model in the loop (side-cam locator mode)
Config:
  - data/calibration/claw_arrival.json  per-object on-top setpoints
        (regenerated by scripts/claw_arrival_calib.py — do not hand-edit)
  - data/calibration/claw_servo.yaml    rig-measured image Jacobian + knobs
        (hand-edited at the rig per §1.3; offline-fit values until then)

Every threshold is a live attribute on ArrivalServo — the UI tunes them at
runtime via tune() (demo-room lighting), nothing here is baked in.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ARRIVAL_JSON = PROJECT_ROOT / "data/calibration/claw_arrival.json"
SERVO_YAML = PROJECT_ROOT / "data/calibration/claw_servo.yaml"
# Rig-measured calibration (scripts/servo_calibrate.py at the arm, 2026-07-14):
# per-object jacobian + setpoint + the z it was measured at. When present it
# is authoritative — it survives claw_arrival.json regeneration by the offline
# calib script.
RIG_CALIB_JSON = PROJECT_ROOT / "data/calibration/claw_servo_calibration.json"
_RIG_KEY_ALIASES = {"knife": "butter_knife"}   # rig file keys by yolo class

# Knobs the UI may change at runtime (whitelist for tune()).
TUNABLE = (
    "conf_floor", "arrival_tol_mm", "tol_cx", "tol_cy", "stay_mm",
    "clip_margin", "max_detect_age_s", "servo_max_step_mm",
    "servo_deadband_mm", "max_corrections",
)


@dataclass
class ArrivalDecision:
    arrived: bool
    box: dict[str, Any] | None      # class-filtered top-conf box (or None)
    err_cx: float = 0.0             # setpoint − box center (normalized, signed)
    err_cy: float = 0.0
    checks: dict[str, bool] = field(default_factory=dict)
    reason: str = ""                # short human-readable verdict for the UI log


class ArrivalServo:
    """Per-object arrival decision + servo-correction step proposal."""

    def __init__(
        self,
        arrival_json: str | Path = ARRIVAL_JSON,
        servo_yaml: str | Path = SERVO_YAML,
        overrides: dict[str, Any] | None = None,
        rig_calib_json: str | Path | None = None,
    ):
        self.setpoints: dict[str, dict[str, Any]] = json.loads(
            Path(arrival_json).read_text()
        )
        cfg = yaml.safe_load(Path(servo_yaml).read_text()) or {}

        # --- arrival knobs (spec §3.2 starting values) ---
        self.conf_floor: float = float(cfg.get("conf_floor", 0.5))
        # Preferred tolerance: millimeters, converted per object through the
        # measured jacobian (tol_cx = |J00|*mm, tol_cy = |J11|*mm). The pixel
        # tolerances below are only the fallback when no jacobian exists.
        # Set 0 to force the manual pixel tolerances.
        self.arrival_tol_mm: float = float(cfg.get("arrival_tol_mm", 12.0))
        self.tol_cx: float = float(cfg.get("tol_cx", 0.06))
        self.tol_cy: float = float(cfg.get("tol_cy", 0.06))
        self.stay_mm: float = float(cfg.get("stay_mm", 15.0))
        self.clip_margin: float = float(cfg.get("clip_margin", 0.005))
        self.max_detect_age_s: float = float(cfg.get("max_detect_age_s", 1.0))

        # --- servo knobs (spec §3.3) ---
        self.servo_max_step_mm: float = float(cfg.get("servo_max_step_mm", 12.0))
        self.servo_deadband_mm: float = float(cfg.get("servo_deadband_mm", 2.0))
        self.max_corrections: int = int(cfg.get("max_corrections", 6))

        # Image Jacobian J = d(cx,cy)/d(arm x,y) in normalized units per mm,
        # measured by the §1.3 rig jogs (or offline-fit from recordings).
        # Per-object because the on-top viewing geometry differs slightly.
        self.calibrated: bool = bool(cfg.get("calibrated", False))
        self.hover_z: float = float(cfg.get("hover_z", 330.0))
        self._jac: dict[str, list[list[float]]] = dict(cfg.get("jacobian", {}))

        # Optional rig-derived setpoint_cy overrides at YOUR hover z (§1.3.4);
        # the shipped json cy comes from a mix of heights (parallax).
        self._cy_override: dict[str, float] = dict(cfg.get("setpoint_cy_at_hover", {}))

        # Rig calibration file wins over everything above: per-object jacobian,
        # live-measured setpoints, and the z each was measured at (= the plane
        # the servo/arrival should run at; board only detects below ~z365).
        self._sp_override: dict[str, tuple[float, float]] = {}
        self._servo_z: dict[str, float] = {}
        rig = Path(rig_calib_json) if rig_calib_json else RIG_CALIB_JSON
        if rig.exists():
            for key, e in (json.loads(rig.read_text()) or {}).items():
                obj = _RIG_KEY_ALIASES.get(key, key)
                if "jacobian_world_to_pixel" in e:
                    self._jac[obj] = e["jacobian_world_to_pixel"]
                if "setpoint_cx" in e and "setpoint_cy" in e:
                    self._sp_override[obj] = (float(e["setpoint_cx"]), float(e["setpoint_cy"]))
                if "hover_z_mm" in e:
                    self._servo_z[obj] = float(e["hover_z_mm"])
            self.calibrated = True

        for k, v in (overrides or {}).items():
            self.tune(k, v)

    # ------------------------------------------------------------------ config
    def tune(self, key: str, value: Any) -> bool:
        """Runtime knob update from the UI. Returns False for unknown keys."""
        if key not in TUNABLE:
            return False
        setattr(self, key, type(getattr(self, key))(value))
        return True

    def knobs(self) -> dict[str, Any]:
        return {k: getattr(self, k) for k in TUNABLE}

    def setpoint(self, object_key: str) -> tuple[float, float, str]:
        sp = self.setpoints[object_key]
        if object_key in self._sp_override:                    # rig-measured
            cx, cy = self._sp_override[object_key]
            return cx, cy, str(sp["yolo_class"])
        cy = self._cy_override.get(object_key, sp["setpoint_cy"])
        return float(sp["setpoint_cx"]), float(cy), str(sp["yolo_class"])

    def servo_z(self, object_key: str) -> float | None:
        """The z the object's jacobian+setpoint were measured at — the plane
        arrival/servo should run on (board only detects below ~z365)."""
        return self._servo_z.get(object_key)

    def tols(self, object_key: str) -> tuple[float, float]:
        """Effective pixel tolerances: arrival_tol_mm through the jacobian
        when available, else the manual tol_cx/tol_cy."""
        if self.arrival_tol_mm > 0:
            try:
                J = self.jacobian(object_key)
                return (max(abs(J[0][0]), 1e-6) * self.arrival_tol_mm,
                        max(abs(J[1][1]), 1e-6) * self.arrival_tol_mm)
            except KeyError:
                pass
        return self.tol_cx, self.tol_cy

    # ------------------------------------------------------------------ arrival
    def best_box(self, boxes: list[dict[str, Any]], object_key: str) -> dict[str, Any] | None:
        """Class-filtered top-confidence box (one object on the table)."""
        cls = self.setpoints[object_key]["yolo_class"]
        matches = [b for b in boxes if b.get("label") == cls]
        return max(matches, key=lambda b: b["conf"]) if matches else None

    def decide(
        self,
        boxes: list[dict[str, Any]],
        object_key: str,
        pred_step_mm: float | None = None,
        detect_age_s: float | None = None,
    ) -> ArrivalDecision:
        """arrived(obj) = A (box on setpoint, unclipped, confident, fresh)
        AND C (model's next step is small). C is skipped when there is no
        model in the loop (pred_step_mm=None, e.g. locator mode)."""
        set_cx, set_cy, _ = self.setpoint(object_key)
        box = self.best_box(boxes, object_key)
        if box is None:
            return ArrivalDecision(False, None, reason="no box of class")

        cx = (box["x1"] + box["x2"]) / 2.0
        cy = (box["y1"] + box["y2"]) / 2.0
        err_cx, err_cy = set_cx - cx, set_cy - cy
        tol_cx, tol_cy = self.tols(object_key)
        m = self.clip_margin
        checks = {
            "conf": box["conf"] >= self.conf_floor,
            "fresh": detect_age_s is None or detect_age_s <= self.max_detect_age_s,
            "cx": abs(err_cx) <= tol_cx,
            "cy": abs(err_cy) <= tol_cy,
            "unclipped": box["x1"] > m and box["y1"] > m
                         and box["x2"] < 1 - m and box["y2"] < 1 - m,
            "model_stays": pred_step_mm is None or pred_step_mm < self.stay_mm,
        }
        arrived = all(checks.values())
        failed = [k for k, ok in checks.items() if not ok]
        reason = "ARRIVED" if arrived else "waiting: " + ",".join(failed)
        return ArrivalDecision(arrived, box, err_cx, err_cy, checks, reason)

    # ------------------------------------------------------------------ servo
    def jacobian(self, object_key: str):
        j = self._jac.get(object_key) or self._jac.get("default")
        if j is None:
            raise KeyError(f"no jacobian for '{object_key}' in {SERVO_YAML.name}")
        return [[float(j[0][0]), float(j[0][1])], [float(j[1][0]), float(j[1][1])]]

    def servo_step(self, decision: ArrivalDecision, object_key: str) -> tuple[float, float] | None:
        """World-frame (dx_mm, dy_mm) that moves the box toward the setpoint:
        step = J⁻¹ @ (setpoint − center), capped to servo_max_step_mm.
        None = don't move (no/unusable/STALE box, or within deadband)."""
        if decision.box is None or not decision.checks.get("conf", False) \
                or not decision.checks.get("fresh", True):
            return None                # never servo on a frozen/stale frame
        (a, b), (c, d) = self.jacobian(object_key)
        det = a * d - b * c
        if abs(det) < 1e-12:
            return None
        dx = (d * decision.err_cx - b * decision.err_cy) / det
        dy = (-c * decision.err_cx + a * decision.err_cy) / det
        norm = (dx * dx + dy * dy) ** 0.5
        if norm < self.servo_deadband_mm:
            return None
        if norm > self.servo_max_step_mm:
            dx, dy = dx / norm * self.servo_max_step_mm, dy / norm * self.servo_max_step_mm
        return dx, dy
